apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: c2-web
  namespace: devsec
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`c2.example.com`)
      kind: Rule
      middlewares:
        - name: c2-redirect-https
      services:
        - name: cloudc2
          port: 80
